### ISSUE TITLE
/bindings/torch/tinycudann/bindings.cpp:88 check failed input.size(1) == n_input_dims()

### ISSUE THREAD

**Issue by dongliangcao** [city-super/GSDF#8]
Hello,

Thanks for your great work. But when I want to use tinycudann to accelerate the training, it always has an error as shown in the title. Do you have any clue how to solve this problem?

Best regards,
Dongliang Cao

**Comment by sgarg18** [comment]
The current definition of self.mlp_cov includes an extra dimension in n_input_dims, specifically +1, which is unnecessary for the input configuration. The model's input dimensionality should only account for feat_dim + 3, as there is no need for the additional dimension. This causes a mismatch between the expected input shape and the actual input provided to the network. To resolve this, n_input_dims needs to be corrected by removing the unnecessary +1 term.

**Comment by fyang235** [comment]
> The current definition of self.mlp_cov includes an extra dimension in n_input_dims, specifically +1, which is unnecessary for the input configuration. The model's input dimensionality should only account for feat_dim + 3, as there is no need for the additional dimension. This causes a mismatch between the expected input shape and the actual input provided to the network. To resolve this, n_input_dims needs to be corrected by removing the unnecessary +1 term.

Thanks for the reply, I encountered the same issue and still do not know how to fix it, could you please be more specific like How to revise the code? By the way, It is good to train when self.use_tcnn = False with the same config.

**Comment by sgarg18** [comment]
in gaussian model.py you have to make changes under

**Comment by fyang235** [comment]
@sgarg18 that works for me, thanks a lot!

**Comment by MulinYu** [comment]
Thanks guys, I'll update the code.
